### ISSUE TITLE
Remove metadata.json from .gitignore

### ISSUE THREAD

**Issue by cyberflow** [librato/statsd-cookbook#105]
Please remove metadata.json from .gitignore

Thanks.

**Comment by mheffner** [comment]
Hi @cyberflow, why is this a problem? That's a file generated from metadata.rb?

**Comment by cyberflow** [comment]
Hi @mheffner,
I generate chef repo over Berkshelf and distribute it on chef server over git hook. After generate chef repo git ignoring metadata.json in cookbook directory and get error when i upload it on chef server.

What reason to keep metadata.json in .gitignore file?

**Comment by mheffner** [comment]
@cyberflow Ok, I've removed it...want to give it a try?
