### ISSUE TITLE
Service fails to start on centos

### ISSUE THREAD

**Issue by mattchurchy** [librato/statsd-cookbook#35]
Service fails to start on centos 6.5 due to the default template getting used instead of the provided rhel template. I tested using the provided .kitchen.yml as well as a `normal` centos 6.5 vm.

Chef client version 11.16.4 and 12+ 

Relevant logging shown below:-

> ```
>  * template[/etc/init/statsd.conf] action create[2014-12-29T21:39:10+00:00] INFO: Processing template[/etc/init/statsd.conf] action create (statsd::default line 77)
> ```
> 
>    [2014-12-29T21:39:10+00:00] DEBUG: providers for generic template resource enabled on node include: [Chef::Provider::Template]
>    [2014-12-29T21:39:10+00:00] DEBUG: providers that refused resource template[/etc/init/statsd.conf] were: []
>    [2014-12-29T21:39:10+00:00] DEBUG: providers that support resource template[/etc/init/statsd.conf] include: [Chef::Provider::Template]
>    [2014-12-29T21:39:10+00:00] DEBUG: providers that survived replacement include: >>[Chef::Provider::Template]
>    [2014-12-29T21:39:10+00:00] DEBUG: touching /etc/init/statsd.conf to create it
>    [2014-12-29T21:39:10+00:00] INFO: template[/etc/init/statsd.conf] created file >/etc/init/statsd.conf
> 
> ```
>    - create new file /etc/init/statsd.conf
> ```
> 
>    [2014-12-29T21:39:10+00:00] DEBUG: calculating checksum of /tmp/chef-rendered-template20141229-2081-2wbzs to compare with
>    [2014-12-29T21:39:10+00:00] DEBUG: running: diff -u /etc/init/statsd.conf /tmp/chef-rendered-template20141229-2081-2wbzs
>   [2014-12-29T21:39:10+00:00] DEBUG: reading modes from /etc/init/statsd.conf file
>   [2014-12-29T21:39:10+00:00] DEBUG: applying mode = 644, uid = 0, gid = 0 to /tmp/chef-rendered-template20141229-2081-2wbzs
>    [2014-12-29T21:39:10+00:00] DEBUG: moving temporary file /tmp/chef-rendered-template20141229-2081-2wbzs into place at /etc/init/statsd.conf
>    [2014-12-29T21:39:10+00:00] INFO: template[/etc/init/statsd.conf] updated file contents /etc/init/statsd.conf
> 
> ```
>    - update content in file /etc/init/statsd.conf from none to 978728
>    --- /etc/init/statsd.conf    2014-12-29 21:39:10.691701025 +0000
>    +++ /tmp/chef-rendered-template20141229-2081-2wbzs   2014-12-29 21:39:10.690700525 +0000
> 
>    @@ -1 +1,29 @@
>    +# statsd - Network daemon for aggregating statistics
> 
>    +#
>    +# This is a network service that receives metric data via UDP from other
>    +# applications. It aggregates this data and flushes it to a storage backend
>    +# (typically Graphite) at regular intervals.
>    +#
>    +description "Network daemon for aggregating statistics"
>    +author      "Librato"
>    +
>    +start on (local-filesystems and net-device-up IFACE!=lo)
>    +
> ```
> 
>    +setuid statsd
>        +setgid statsd
>        +
>        +respawn
>        +respawn limit 10 5
>        +
>        +chdir /usr/share/statsd
> 
> ```
>    +
>    +pre-start script
>    +    NODE_BIN=$(which nodejs || which node)
>    +    [ -n $NODE_BIN ] || { stop; exit 0; }
>    +end script
> 
> 
>    +script
>    +    NODE_BIN=$(which nodejs || which node)
>    +    $NODE_BIN stats.js /etc/statsd/config.js 2>&1 >> /var/log/statsd.log
>    +end script
> ```

**Comment by begriffs** [comment]
I created an init.d script that works on Amazon Linux. Here it is if you want to incorporate it into the recipe:

https://gist.github.com/begriffs/e80eb752a00fc1d03220

**Comment by mheffner** [comment]
fixed in #203
